apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: phanindravedula/demoapp:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
           - name: PASSWORD
             valueFrom:
               secretKeyRef:
                 name: flask-secrets
                 key: PASSWORD
           - name: VARIABLE_MSG
             valueFrom:
               configMapKeyRef:
                 name: message-configmap
                 key: VARIABLE_MSG
      tolerations:
      - key: "key1"
        operator: "Exists"
        effect: "NoSchedule"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 31930
    protocol: TCP
    targetPort: 8000
  selector:
    app: flaskapi
