apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: john-finance-rolebinding
  namespace: finance
  resourceVersion: "8817"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: john-finance
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: john
