apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: john-finance
  namespace: finance
  resourceVersion: "8986"
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - get
  - list
  - create
